### ISSUE TITLE
Adobe SDK Depreciation

### ISSUE THREAD

**Issue by alien3d** [npomfret/react-native-image-tools#15]
[https://blog.creativesdk.com/2017/09/important-update-to-the-creative-sdk-end-of-support-for-the-image-editor-ui-color-ui-market-browser-and-labs-components/](url)

Your plugin work on android, but sadly  for all of us..  @npomfret

**Comment by EyalSi** [comment]
The plugin is still working on Android and iOS 11.

**Comment by alien3d** [comment]
they bring up new version .. @npomfret  @EyalSi  ..   i thought the project was dead .. 

This package contains the Adobe Creative SDK frameworks for iOS version 10.0 and above.

For documentation on the SDK, including the getting started guide, see https://creativesdk.adobe.com/docs/

** new sdk update only for ios ..  android nada

**Comment by npomfret** [comment]
Really?  Well if the creative sdk is still running we could resurrect this repo.  Except I don't have much time.  Happy to take on contributors if anyone is will to help?

**Comment by alien3d** [comment]
when i testing this morning a bit odd.. I think you  should close it.  I previously apply key for android and it work..  but  when i try to do in web based same key..It said depreciated..  

For now, no alternative for photo editor like adobe creative except for https://www.dsphotoeditor.com/
They provide free for non in app application.. I try to email them and ask in the future, are they have api for react-native

**Comment by Prashant-Pandey** [comment]
As Adobe creative SDK is Depreciated, I'm not been able to get AdobeCreativeSDKImage.framework file as well as some elements have been removed from AdobeCreativeSDKCore.framework. @npomfret 
 Can you help me with that ??

**Comment by npomfret** [comment]
No, that project and this one are dead
