### ISSUE TITLE
react-native-image-tools:compileReleaseJavaWithJavac FAILED

### ISSUE THREAD

**Issue by junaidsubhni** [npomfret/react-native-image-tools#17]
\node_modules\react-native-image-tools\android\src\main\java\com\pomocorp\rnimagetools\RNImageToolsPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-image-tools:compileReleaseJavaWithJavac FAILED

**Comment by EyalSi** [comment]
just remove the line which includes this @override, and it's working fine...

**Comment by junaidsubhni** [comment]
@EyalSi yes i did that and it was fine
