### ISSUE TITLE
iOS throws an error while assets-library is the source of image.

### ISSUE THREAD

**Issue by srameshr** [npomfret/react-native-image-tools#9]
```
index.ios.bundle?platform=ios&dev=true&minify=false:10560 Exception '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[5]' was thrown while invoking openEditor on target RNImageTools with params (
        {
        imageUri = "assets-library://asset/asset.JPG?id=9F983DBA-EC35-42B8-8773-B597CF782EDD&ext=JPG";
        quality = 90;
        saveTo = photo;
    },
    3524,
    3525
)
```
The plugin works fine if I provide, ```http``` or ```file://``` uri.

**Comment by srameshr** [comment]
@npomfret Could you look into this?

**Comment by npomfret** [comment]
Will do, don't think it's a difficult fix but am struggling for time at the moment.

**Comment by srameshr** [comment]
@npomfret Thank you! This and accepting array of tools would really help!

**Comment by srameshr** [comment]
@npomfret Any updates on this?

**Comment by srameshr** [comment]
@npomfret If its a simple fix can you please look into this. I went over iOS code, but I  am not able to figure it out. I have never used objective-c

**Comment by srameshr** [comment]
Anybody able to fix this damn thing?

**Comment by srameshr** [comment]
I fixed it with the help of an iOS dev friend. This occurs on iOS 9.0 because of this line 
```
 NSISO8601DateFormatter *dateFormatter = [[NSISO8601DateFormatter alloc] init];
```

This formatter is iOS 10+ only.

Replaced it with:
```
NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    formatter.dateFormat = @"h:mm a, d MMM";
    NSString *timestamp = [formatter stringFromDate:creationDate];
```

**Comment by YahyaBagia** [comment]
You have to link CameraRoll (RN's library) to your iOS project. See [this](https://stackoverflow.com/questions/43234181/react-native-how-to-link-official-libraries-like-cameraroll) SO link for instructions.

- Drag the node_modules/react-native/Libraries/CameraRoll/RCTCameraRoll.xcodeproj file in your Libraries folder in Xcode
- in Xcode Build Phases -> Link Binary With Libraries -> then press + sign and add the libRCTCameraRoll.a
- Recompile your app

**Comment by srameshr** [comment]
This is a better one https://github.com/prscX/react-native-photo-editor/issues/1

**Comment by npomfret** [comment]
@srameshr thanks for the link - hope this is of use to people.

**Comment by srameshr** [comment]
@npomfret  Could you put it in your readme file?
